### PR TITLE
Initial CoreBundle import

### PR DESCRIPTION
**Pull request by core23**
Initial import of the CoreBundle (https://github.com/sonata-project/SonataCoreBundle/commit/028b3c3191a9906a88a49dbded91a03d6dbe901f)

## To do
- [x] Dependens on new `sonata-project/doctrine-extensions` release
- [x] Update the tests
- [x] Update the documentation
- [ ] Test it on an original project

### CODE REVIEW

**Comment by core23** [comment]
Please review @sonata-project/contributors

**Comment by core23** [comment]
Can someone else please review? @greg0ire @kunicmarko20

**Comment by greg0ire** [comment]
That's a big one, I'll review it when I get back from holidays

**Comment by OskarStark** [comment]
Can we close this @core23?

**Pull request closed without merging**
