### PR TITLE
Add probot settings to manage repository metadata

### PR DESCRIPTION
**Pull request by core23**
## Subject

Refs: https://github.com/sonata-project/dev-kit/issues/822#issuecomment-674417996

I am targeting this branch, because is a pedantic change.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Should we add this to dev-kit instead and dispatch files ?

There is already a variable for the name.
The homepage is a constant.
Topics (and description) could be another config key.

**Comment by core23** [comment]
> Should we add this to dev-kit instead and dispatch files ?
> 
> There is already a variable for the name.
> The homepage is a constant.
> Topics (and description) could be another config key.

IMHO it doesn't make any sense. The settings file is pretty static and doesn't need any updates. Managing static config keys in an other config system (dev-kit) is overkill.

This is just a first test, if probot is working on our repos.

**Comment by VincentLanglet** [comment]
> > Should we add this to dev-kit instead and dispatch files ?
> > There is already a variable for the name.
> > The homepage is a constant.
> > Topics (and description) could be another config key.
> 
> IMHO it doesn't make any sense. The settings file is pretty static and doesn't need any updates. Managing static config keys in an other config system (dev-kit) is overkill.

A lot of dev-kit dispatched files are static and doesn't need a lot of updates, but
- dev-kit helps to have consistency: We will want a similar probot config for every repo.
- dev-kit helps to have automation: For example, we could have automation for the `[deprecated]` or `[abandonned]` prefix.

> This is just a first test, if probot is working on our repos.

Sure

**Comment by core23** [comment]
@sonata-project/contributors WDYT? Should we use probot or should we add these options to the dev-kit. Who would like to add these features to dev-kit?

**Comment by jordisala1991** [comment]
IMO devkit should dispatch this files

**Comment by VincentLanglet** [comment]
> IMO devkit should dispatch this files

I agree, this way we would have probot on every project.

**Review by phansys — DISMISSED** [review]

**Comment by VincentLanglet** [comment]
> > IMO devkit should dispatch this files
> 
> I agree, this way we would have probot on every project.
> 
> I can work on this this We (if I don't forget) if you want @core23.

I started something https://github.com/sonata-project/dev-kit/pull/920

**Comment by core23** [comment]
As long as we are still planing to use probot. Can we merge this PR to test if it works as expected?

**Review by VincentLanglet — APPROVED** [review]

**Review by VincentLanglet — CHANGES_REQUESTED** [review]
We may not need probot after all.

Somethings seems already implemented in dev-kit: https://github.com/sonata-project/dev-kit/blob/master/src/Command/DispatchCommand.php#L141

**Comment by core23** [comment]
We don't need probot anymore

**Pull request closed without merging**
